[package]
name = "brain-assistant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
colored = "2.0.0"
nom = "7.1.3"
num-bigint = "0.4.3"
num-traits = "0.2.15"
