name: Check Changelog

on:
  pull_request:
    branches: [ main ]

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare repo
      run: |
        git fetch

    - name: Check changelog history
      run: |

        if git diff --exit-code origin/${{ github.event.pull_request.base.ref }} HEAD -- CHANGELOG.md ; then
          echo "Changelog not updated"
          exit 1
        fi
